[package]
name = "andromeda-bench"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
andromeda-error.workspace = true
andromeda-hardware.workspace = true
andromeda-observe.workspace = true
andromeda-srpl.workspace = true
andromeda-storage.workspace = true
andromeda-time.workspace = true
andromeda-types.workspace = true
