#![forbid(unsafe_code)]

//! Protobuf determinism and schema compatibility validation tests.
//!
//! These tests ensure that:
//! - Serialization is deterministic (same message → same bytes every time)
//! - Round-trip serialization preserves field values
//! - Edge cases (empty, zero, max values) are handled correctly
//! - Schema changes maintain wire compatibility

use proptest::prelude::*;
use prost::Message;

// Import generated protobuf message types
// (these would be generated by prost from the .proto files)
use andromeda_proto::generated::andromeda::protocol::v1::{
    ErrorEnvelope, FrameEnvelope, ProtocolVersion, RpcBatch, RpcCompletion,
};

use andromeda_proto::generated::andromeda::contract::v1::{
    CatalogProcedureManifestResolutionRequest, CatalogProcedureManifestResolutionResponse,
    ProcedureManifest, ProtocolLayout as GeneratedProtocolLayout, RequiredPermission,
    StructuredObjectHeader, catalog_procedure_manifest_resolution_request,
};
use andromeda_proto::{
    validate_catalog_procedure_manifest_resolution_request,
    validate_catalog_procedure_manifest_resolution_response,
};

#[test]
fn test_protocol_version_deterministic_serialization() {
    let version = ProtocolVersion { major: 1, minor: 0 };

    let bytes1 = version.encode_to_vec();
    let bytes2 = version.encode_to_vec();

    assert_eq!(bytes1, bytes2, "Multiple serializations must be identical");
}

#[test]
fn test_protocol_version_roundtrip() {
    let original = ProtocolVersion { major: 1, minor: 5 };

    let bytes = original.encode_to_vec();
    let decoded =
        ProtocolVersion::decode(bytes.as_slice()).expect("Deserialization should succeed");

    assert_eq!(original, decoded, "Round-trip must preserve all fields");
}

#[test]
fn test_frame_envelope_deterministic_serialization() {
    let envelope = FrameEnvelope {
        protocol_version: Some(ProtocolVersion { major: 1, minor: 0 }),
        contract_hash: vec![42u8; 32],
        catalog_version: 12345,
        request_id: 10,
        session_id: 20,
        tx_id: Some(30),
        payload_kind: 5, // RPC_EXECUTE_REQUEST
        payload: vec![1, 2, 3, 4, 5],
    };

    let bytes1 = envelope.encode_to_vec();
    let bytes2 = envelope.encode_to_vec();
    let bytes3 = envelope.encode_to_vec();

    assert_eq!(bytes1, bytes2, "First and second serializations must match");
    assert_eq!(bytes2, bytes3, "Second and third serializations must match");
}

#[test]
fn test_frame_envelope_edge_cases() {
    // Test: empty contract hash (should not panic, should serialize)
    let envelope_empty_hash = FrameEnvelope {
        protocol_version: Some(ProtocolVersion { major: 1, minor: 0 }),
        contract_hash: vec![],
        catalog_version: 0,
        request_id: 0,
        session_id: 0,
        tx_id: None,
        payload_kind: 1, // HELLO
        payload: vec![],
    };

    let bytes = envelope_empty_hash.encode_to_vec();
    let decoded = FrameEnvelope::decode(bytes.as_slice()).expect("Deserialize with empty hash");

    assert_eq!(envelope_empty_hash, decoded);
}

#[test]
fn test_rpc_batch_deterministic_serialization() {
    let batch = RpcBatch {
        result_name: "users".to_string(),
        batch_index: 1,
        rows_emitted: 100,
        structured_payload: vec![0, 1, 2, 3, 255],
        row_count_exact: Some(1000),
        terminal_batch: false,
    };

    let bytes1 = batch.encode_to_vec();
    let bytes2 = batch.encode_to_vec();

    assert_eq!(bytes1, bytes2, "Batch serializations must be identical");
}

#[test]
fn test_rpc_completion_all_fields() {
    let completion = RpcCompletion {
        status: 1, // STATUS_COMMITTED
        rows_affected: Some(50),
        tx_id: Some(99),
        request_id: Some(10),
        session_id: Some(20),
        trace_id: Some("trace-001".to_string()),
        transaction_outcome: 2, // TRANSACTION_OUTCOME_COMMITTED
        durable_lsn: Some(5000),
        result_row_counts: vec![],
    };

    let bytes = completion.encode_to_vec();
    let decoded = RpcCompletion::decode(bytes.as_slice()).expect("Deserialize completion");

    assert_eq!(completion, decoded);
}

#[test]
fn test_error_envelope_deterministic_serialization() {
    let error = ErrorEnvelope {
        request_id: Some(10),
        session_id: Some(20),
        trace_id: Some("trace-001".to_string()),
        family: 1, // ERROR_FAMILY_PROTOCOL
        code: "PROTOCOL_ERROR".to_string(),
        message: "Invalid frame type".to_string(),
        transaction_effect: 1, // TRANSACTION_EFFECT_NO_TRANSACTION
        retry_disposition: 1,  // RETRY_DISPOSITION_NOT_RETRYABLE
        retry_after_ms: None,
        backpressure: None,
    };

    let bytes1 = error.encode_to_vec();
    let bytes2 = error.encode_to_vec();

    assert_eq!(bytes1, bytes2, "Error envelope serializations must match");
}

#[test]
fn test_structured_object_header_deterministic_serialization() {
    let header = StructuredObjectHeader {
        name: "result_set".to_string(),
        contract_hash: vec![42u8; 32],
        descriptor_hash: vec![43u8; 32],
        row_count_exact: 1000,
        column_count: 5,
        layout: 1, // LAYOUT_ROW_MAJOR
        payload_length: 50000,
        payload_checksum: Some(0xDEADBEEF),
        max_payload_length: Some(100000),
        fields: vec![],
        row_count_policy: 2, // ROW_COUNT_REQUIREMENT_EXACT_IF_KNOWN
    };

    let bytes1 = header.encode_to_vec();
    let bytes2 = header.encode_to_vec();

    assert_eq!(
        bytes1, bytes2,
        "Structured object headers must serialize identically"
    );
}

#[test]
fn test_catalog_manifest_resolution_messages_roundtrip_without_json_or_grpc() {
    let request = CatalogProcedureManifestResolutionRequest {
        protocol_major: 1,
        protocol_minor: 0,
        request_id: 77,
        trace_id: Some("trace-manifest-77".to_string()),
        selector: Some(
            catalog_procedure_manifest_resolution_request::Selector::ProcedureName(
                "Inventory.ReserveStock".to_string(),
            ),
        ),
        expected_contract_hash: Some(vec![0x11; 32]),
        expected_catalog_version: Some(9),
        require_source_generator_ready: true,
    };

    let request_bytes = request.encode_to_vec();
    let decoded_request =
        CatalogProcedureManifestResolutionRequest::decode(request_bytes.as_slice())
            .expect("manifest resolution request must decode");
    assert_eq!(request, decoded_request);
    validate_catalog_procedure_manifest_resolution_request(&request)
        .expect("manifest resolution request must satisfy boundary validation");

    let response = CatalogProcedureManifestResolutionResponse {
        protocol_major: 1,
        protocol_minor: 0,
        request_id: 77,
        trace_id: Some("trace-manifest-77".to_string()),
        status: 1, // STATUS_RESOLVED
        manifest: Some(ProcedureManifest {
            procedure_id: 42,
            procedure_name: "Inventory.ReserveStock".to_string(),
            contract_hash: vec![0x11; 32],
            catalog_version: 9,
            protocol_layout: Some(GeneratedProtocolLayout {
                descriptor_set_hash: vec![0x22; 32],
                frame_envelope_hash: vec![0x33; 32],
                protocol_package: "andromeda.protocol.v1".to_string(),
                contract_package: "andromeda.contract.v1".to_string(),
            }),
            result_streams: vec![],
            policy_version: vec![0x44; 32],
            required_permissions: vec![RequiredPermission {
                id: "andromeda.execute_procedure".to_string(),
                family: "application".to_string(),
            }],
        }),
        resolved_contract_hash: Some(vec![0x11; 32]),
        resolved_catalog_version: Some(9),
        current_catalog_version: Some(9),
        diagnostic_code: None,
    };

    let response_bytes_1 = response.encode_to_vec();
    let response_bytes_2 = response.encode_to_vec();
    assert_eq!(
        response_bytes_1, response_bytes_2,
        "manifest resolution response encoding must be deterministic"
    );

    let decoded_response =
        CatalogProcedureManifestResolutionResponse::decode(response_bytes_1.as_slice())
            .expect("manifest resolution response must decode");
    assert_eq!(response, decoded_response);
    validate_catalog_procedure_manifest_resolution_response(&response)
        .expect("manifest resolution response must satisfy boundary validation");
}

proptest! {
    #[test]
    fn prop_protocol_version_roundtrip(major in 0u32..=1000, minor in 0u32..=1000) {
        let version = ProtocolVersion { major, minor };
        let bytes = version.encode_to_vec();
        let decoded = ProtocolVersion::decode(bytes.as_slice())
            .expect("Decode should succeed");

        prop_assert_eq!(version, decoded);
    }

    #[test]
    fn prop_frame_envelope_determinism(
        catalog_version in 0u64..=u64::MAX,
        request_id in 0u64..=u64::MAX,
        session_id in 0u64..=u64::MAX,
    ) {
        let envelope = FrameEnvelope {
            protocol_version: Some(ProtocolVersion { major: 1, minor: 0 }),
            contract_hash: vec![42u8; 32],
            catalog_version,
            request_id,
            session_id,
            tx_id: None,
            payload_kind: 5,
            payload: vec![1, 2, 3],
        };

        let bytes1 = envelope.encode_to_vec();
        let bytes2 = envelope.encode_to_vec();

        prop_assert_eq!(bytes1, bytes2, "Must serialize deterministically");
    }

    #[test]
    fn prop_rpc_batch_roundtrip(
        batch_index in 0u64..=1000,
        rows_emitted in 0u64..=1_000_000,
    ) {
        let batch = RpcBatch {
            result_name: "result".to_string(),
            batch_index,
            rows_emitted,
            structured_payload: vec![],
            row_count_exact: None,
            terminal_batch: false,
        };

        let bytes = batch.encode_to_vec();
        let decoded = RpcBatch::decode(bytes.as_slice())
            .expect("Decode should succeed");

        prop_assert_eq!(batch, decoded);
    }
}

// Test: Verify known hash values for specific messages (contract binding)
#[test]
fn test_known_message_encoding_contracts() {
    // These are canonical encodings; if they change, it indicates schema drift.

    // ProtocolVersion(1, 0) must always encode field 1 as varint 1. The
    // zero-valued minor field is omitted by Protobuf canonical encoding.
    let version_1_0 = ProtocolVersion { major: 1, minor: 0 };
    let expected_bytes = vec![0x08, 0x01];
    let actual_bytes = version_1_0.encode_to_vec();

    assert_eq!(
        actual_bytes, expected_bytes,
        "ProtocolVersion(1, 0) encoding contract changed; verify compatibility"
    );
}

#[test]
fn test_field_presence_preservation() {
    // Optional fields must preserve None/Some distinction
    let completion_with_lsn = RpcCompletion {
        status: 1,
        rows_affected: None,
        tx_id: None,
        request_id: None,
        session_id: None,
        trace_id: None,
        transaction_outcome: 2,
        durable_lsn: Some(12345),
        result_row_counts: vec![],
    };

    let completion_without_lsn = RpcCompletion {
        status: 1,
        rows_affected: None,
        tx_id: None,
        request_id: None,
        session_id: None,
        trace_id: None,
        transaction_outcome: 2,
        durable_lsn: None,
        result_row_counts: vec![],
    };

    let bytes_with = completion_with_lsn.encode_to_vec();
    let bytes_without = completion_without_lsn.encode_to_vec();

    assert_ne!(
        bytes_with, bytes_without,
        "Optional field presence must affect encoding"
    );

    // Verify roundtrip preserves the distinction
    let decoded_with = RpcCompletion::decode(bytes_with.as_slice()).unwrap();
    let decoded_without = RpcCompletion::decode(bytes_without.as_slice()).unwrap();

    assert_eq!(decoded_with.durable_lsn, Some(12345));
    assert_eq!(decoded_without.durable_lsn, None);
}

#[test]
fn test_no_codec_panics_on_malformed_input() {
    // Verify that malformed bytes don't cause panics
    let malformed_inputs = vec![
        vec![],                             // Empty
        vec![0xFF, 0xFF, 0xFF, 0xFF],       // Invalid varint
        vec![0x08, 0xFF, 0xFF, 0xFF, 0xFF], // Truncated field
    ];

    for malformed in malformed_inputs {
        // These should not panic; they may error, but not panic
        let result = FrameEnvelope::decode(malformed.as_slice());
        // We don't assert success, just that it doesn't panic
        let _ = result;
    }
}
