#![forbid(unsafe_code)]

//! Protobuf determinism and schema compatibility validation tests.
//!
//! These tests ensure that:
//! - Serialization is deterministic (same message → same bytes every time)
//! - Round-trip serialization preserves field values
//! - Edge cases (empty, zero, max values) are handled correctly
//! - Schema changes maintain wire compatibility

use proptest::prelude::*;
use prost::Message;

// Import generated protobuf message types
// (these would be generated by prost from the .proto files)
use andromeda_proto::generated::andromeda::protocol::v1::{
    ErrorEnvelope, FrameEnvelope, ProtocolVersion, RpcBatch, RpcCompletion,
};

use andromeda_proto::generated::andromeda::contract::v1::{
    CatalogProcedureManifestResolutionRequest, CatalogProcedureManifestResolutionResponse,
    ColumnDescriptor, ProcedureManifest, ProtocolLayout as GeneratedProtocolLayout,
    RequiredPermission, ResultStreamDescriptor, StructuredObjectHeader,
    catalog_procedure_manifest_resolution_request, result_stream_descriptor,
};
use andromeda_proto::{
    RpcCompletionStatus, validate_catalog_procedure_manifest_resolution_request,
    validate_catalog_procedure_manifest_resolution_response, validate_generated_rpc_completion,
};

fn valid_generated_result_stream() -> ResultStreamDescriptor {
    ResultStreamDescriptor {
        stream_name: "Reservation".to_string(),
        columns: vec![ColumnDescriptor {
            name: "Reserved".to_string(),
            ordinal: 0,
            type_name: "bool".to_string(),
        }],
        cardinality: result_stream_descriptor::Cardinality::ExactlyOne as i32,
        row_count_requirement: result_stream_descriptor::RowCountRequirement::ExactRequired as i32,
        row_count_exact: Some(1),
        row_count_max: Some(1),
    }
}

fn valid_generated_manifest() -> ProcedureManifest {
    ProcedureManifest {
        procedure_id: 42,
        procedure_name: "Inventory.ReserveStock".to_string(),
        contract_hash: vec![0x11; 32],
        catalog_version: 9,
        protocol_layout: Some(GeneratedProtocolLayout {
            descriptor_set_hash: vec![0x22; 32],
            frame_envelope_hash: vec![0x33; 32],
            protocol_package: "andromeda.protocol.v1".to_string(),
            contract_package: "andromeda.contract.v1".to_string(),
        }),
        result_streams: vec![valid_generated_result_stream()],
        policy_version: vec![0x44; 32],
        required_permissions: vec![RequiredPermission {
            id: "andromeda.execute_procedure".to_string(),
            family: "application".to_string(),
        }],
        stats_version: Some(5),
    }
}

fn resolved_response_with_manifest(
    manifest: ProcedureManifest,
) -> CatalogProcedureManifestResolutionResponse {
    CatalogProcedureManifestResolutionResponse {
        protocol_major: 1,
        protocol_minor: 0,
        request_id: 77,
        trace_id: Some("trace-manifest-77".to_string()),
        status: 1,
        manifest: Some(manifest),
        resolved_contract_hash: Some(vec![0x11; 32]),
        resolved_catalog_version: Some(9),
        current_catalog_version: Some(9),
        diagnostic_code: None,
    }
}

#[test]
fn test_protocol_version_deterministic_serialization() {
    let version = ProtocolVersion { major: 1, minor: 0 };

    let bytes1 = version.encode_to_vec();
    let bytes2 = version.encode_to_vec();

    assert_eq!(bytes1, bytes2, "Multiple serializations must be identical");
}

#[test]
fn test_protocol_version_roundtrip() {
    let original = ProtocolVersion { major: 1, minor: 5 };

    let bytes = original.encode_to_vec();
    let decoded =
        ProtocolVersion::decode(bytes.as_slice()).expect("Deserialization should succeed");

    assert_eq!(original, decoded, "Round-trip must preserve all fields");
}

#[test]
fn test_frame_envelope_deterministic_serialization() {
    let envelope = FrameEnvelope {
        protocol_version: Some(ProtocolVersion { major: 1, minor: 0 }),
        contract_hash: vec![42u8; 32],
        catalog_version: 12345,
        request_id: 10,
        session_id: 20,
        tx_id: Some(30),
        payload_kind: 5, // RPC_EXECUTE_REQUEST
        payload: vec![1, 2, 3, 4, 5],
    };

    let bytes1 = envelope.encode_to_vec();
    let bytes2 = envelope.encode_to_vec();
    let bytes3 = envelope.encode_to_vec();

    assert_eq!(bytes1, bytes2, "First and second serializations must match");
    assert_eq!(bytes2, bytes3, "Second and third serializations must match");
}

#[test]
fn test_frame_envelope_edge_cases() {
    // Test: empty contract hash (should not panic, should serialize)
    let envelope_empty_hash = FrameEnvelope {
        protocol_version: Some(ProtocolVersion { major: 1, minor: 0 }),
        contract_hash: vec![],
        catalog_version: 0,
        request_id: 0,
        session_id: 0,
        tx_id: None,
        payload_kind: 1, // HELLO
        payload: vec![],
    };

    let bytes = envelope_empty_hash.encode_to_vec();
    let decoded = FrameEnvelope::decode(bytes.as_slice()).expect("Deserialize with empty hash");

    assert_eq!(envelope_empty_hash, decoded);
}

#[test]
fn test_rpc_batch_deterministic_serialization() {
    let batch = RpcBatch {
        result_name: "users".to_string(),
        batch_index: 1,
        rows_emitted: 100,
        structured_payload: vec![0, 1, 2, 3, 255],
        row_count_exact: Some(1000),
        terminal_batch: false,
    };

    let bytes1 = batch.encode_to_vec();
    let bytes2 = batch.encode_to_vec();

    assert_eq!(bytes1, bytes2, "Batch serializations must be identical");
}

#[test]
fn test_rpc_completion_all_fields() {
    let completion = RpcCompletion {
        status: 1, // STATUS_COMMITTED
        rows_affected: Some(50),
        tx_id: Some(99),
        request_id: Some(10),
        session_id: Some(20),
        trace_id: Some("trace-001".to_string()),
        transaction_outcome: 2, // TRANSACTION_OUTCOME_COMMITTED
        durable_lsn: Some(5000),
        result_row_counts: vec![],
    };

    let bytes = completion.encode_to_vec();
    let decoded = RpcCompletion::decode(bytes.as_slice()).expect("Deserialize completion");

    assert_eq!(completion, decoded);
}

#[test]
fn rpc_completion_status_policy_rejects_unspecified_and_unknown_wire_codes() {
    use andromeda_proto::generated::andromeda::protocol::v1::rpc_completion::Status;

    assert_eq!(Status::Unspecified as i32, 0);
    assert!(RpcCompletionStatus::from_terminal_code(Status::Unspecified as u32).is_none());

    for status in [
        Status::Committed,
        Status::RolledBack,
        Status::FailedBeforeTransaction,
        Status::Cancelled,
        Status::Poisoned,
        Status::PermissionDenied,
        Status::ContractRejected,
        Status::SystemUnavailable,
    ] {
        assert!(
            RpcCompletionStatus::from_terminal_code(status as u32).is_some(),
            "{status:?} must remain an accepted governed completion status"
        );
    }

    for unknown_code in [9_u32, 12, u32::MAX] {
        let completion = RpcCompletion {
            status: unknown_code as i32,
            rows_affected: None,
            tx_id: None,
            request_id: Some(10),
            session_id: Some(20),
            trace_id: Some(format!("trace-unknown-status-{unknown_code}")),
            transaction_outcome: 1,
            durable_lsn: None,
            result_row_counts: vec![],
        };

        let decoded = RpcCompletion::decode(completion.encode_to_vec().as_slice())
            .expect("unknown enum value must decode as raw protobuf integer");

        assert_eq!(decoded.status, unknown_code as i32);
        assert!(
            RpcCompletionStatus::from_terminal_code(unknown_code).is_none(),
            "unknown protobuf completion status {unknown_code} must not map to a domain status"
        );
    }
}

#[test]
fn generated_rpc_completion_boundary_validation_rejects_unknown_codes_without_panic() {
    let valid = RpcCompletion {
        status: 1,
        rows_affected: Some(50),
        tx_id: Some(99),
        request_id: Some(10),
        session_id: Some(20),
        trace_id: Some("trace-001".to_string()),
        transaction_outcome: 2,
        durable_lsn: Some(5000),
        result_row_counts: vec![],
    };
    validate_generated_rpc_completion(&valid)
        .expect("valid generated completion must satisfy boundary validation");

    for (field, invalid) in [
        (
            "status unspecified",
            RpcCompletion {
                status: 0,
                ..valid.clone()
            },
        ),
        (
            "status unknown",
            RpcCompletion {
                status: 12,
                ..valid.clone()
            },
        ),
        (
            "status negative",
            RpcCompletion {
                status: -1,
                ..valid.clone()
            },
        ),
        (
            "transaction outcome unspecified",
            RpcCompletion {
                transaction_outcome: 0,
                ..valid.clone()
            },
        ),
        (
            "transaction outcome unknown",
            RpcCompletion {
                transaction_outcome: 99,
                ..valid.clone()
            },
        ),
    ] {
        assert!(
            validate_generated_rpc_completion(&invalid).is_err(),
            "{field} must be rejected by generated completion boundary validation"
        );
    }

    let missing_lsn = RpcCompletion {
        durable_lsn: None,
        ..valid
    };
    assert!(
        validate_generated_rpc_completion(&missing_lsn).is_err(),
        "committed completion requires durable LSN evidence"
    );
}

#[test]
fn test_error_envelope_deterministic_serialization() {
    let error = ErrorEnvelope {
        request_id: Some(10),
        session_id: Some(20),
        trace_id: Some("trace-001".to_string()),
        family: 1, // ERROR_FAMILY_PROTOCOL
        code: "PROTOCOL_ERROR".to_string(),
        message: "Invalid frame type".to_string(),
        transaction_effect: 1, // TRANSACTION_EFFECT_NO_TRANSACTION
        retry_disposition: 1,  // RETRY_DISPOSITION_NOT_RETRYABLE
        retry_after_ms: None,
        backpressure: None,
    };

    let bytes1 = error.encode_to_vec();
    let bytes2 = error.encode_to_vec();

    assert_eq!(bytes1, bytes2, "Error envelope serializations must match");
}

#[test]
fn test_structured_object_header_deterministic_serialization() {
    let header = StructuredObjectHeader {
        name: "result_set".to_string(),
        contract_hash: vec![42u8; 32],
        descriptor_hash: vec![43u8; 32],
        row_count_exact: 1000,
        column_count: 5,
        layout: 1, // LAYOUT_ROW_MAJOR
        payload_length: 50000,
        payload_checksum: Some(0xDEADBEEF),
        max_payload_length: Some(100000),
        fields: vec![],
        row_count_policy: 2, // ROW_COUNT_REQUIREMENT_EXACT_IF_KNOWN
    };

    let bytes1 = header.encode_to_vec();
    let bytes2 = header.encode_to_vec();

    assert_eq!(
        bytes1, bytes2,
        "Structured object headers must serialize identically"
    );
}

#[test]
fn test_catalog_manifest_resolution_messages_roundtrip_without_json_or_grpc() {
    let request = CatalogProcedureManifestResolutionRequest {
        protocol_major: 1,
        protocol_minor: 0,
        request_id: 77,
        trace_id: Some("trace-manifest-77".to_string()),
        selector: Some(
            catalog_procedure_manifest_resolution_request::Selector::ProcedureName(
                "Inventory.ReserveStock".to_string(),
            ),
        ),
        expected_contract_hash: Some(vec![0x11; 32]),
        expected_catalog_version: Some(9),
        require_source_generator_ready: true,
    };

    let request_bytes = request.encode_to_vec();
    let decoded_request =
        CatalogProcedureManifestResolutionRequest::decode(request_bytes.as_slice())
            .expect("manifest resolution request must decode");
    assert_eq!(request, decoded_request);
    validate_catalog_procedure_manifest_resolution_request(&request)
        .expect("manifest resolution request must satisfy boundary validation");

    let response = CatalogProcedureManifestResolutionResponse {
        protocol_major: 1,
        protocol_minor: 0,
        request_id: 77,
        trace_id: Some("trace-manifest-77".to_string()),
        status: 1, // STATUS_RESOLVED
        manifest: Some(valid_generated_manifest()),
        resolved_contract_hash: Some(vec![0x11; 32]),
        resolved_catalog_version: Some(9),
        current_catalog_version: Some(9),
        diagnostic_code: None,
    };

    let response_bytes_1 = response.encode_to_vec();
    let response_bytes_2 = response.encode_to_vec();
    assert_eq!(
        response_bytes_1, response_bytes_2,
        "manifest resolution response encoding must be deterministic"
    );

    let decoded_response =
        CatalogProcedureManifestResolutionResponse::decode(response_bytes_1.as_slice())
            .expect("manifest resolution response must decode");
    assert_eq!(response, decoded_response);
    validate_catalog_procedure_manifest_resolution_response(&response)
        .expect("manifest resolution response must satisfy boundary validation");
}

#[test]
fn generated_manifest_boundary_validation_rejects_invalid_result_stream_metadata() {
    let mut missing_exact = valid_generated_manifest();
    missing_exact.result_streams[0].row_count_exact = None;
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&resolved_response_with_manifest(
            missing_exact
        ))
        .is_err(),
        "exact-required result streams must carry row_count_exact"
    );

    let mut unknown_cardinality = valid_generated_manifest();
    unknown_cardinality.result_streams[0].cardinality = 99;
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&resolved_response_with_manifest(
            unknown_cardinality
        ))
        .is_err(),
        "unknown generated cardinality codes must be rejected"
    );

    let mut empty_column_type = valid_generated_manifest();
    empty_column_type.result_streams[0].columns[0].type_name = " ".to_string();
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&resolved_response_with_manifest(
            empty_column_type
        ))
        .is_err(),
        "generated column descriptors must not use empty type names"
    );

    let mut empty_columns = valid_generated_manifest();
    empty_columns.result_streams[0].columns.clear();
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&resolved_response_with_manifest(
            empty_columns
        ))
        .is_err(),
        "generated result stream descriptors must carry typed columns"
    );

    let mut sparse_columns = valid_generated_manifest();
    sparse_columns.result_streams[0].columns[0].ordinal = 1;
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&resolved_response_with_manifest(
            sparse_columns
        ))
        .is_err(),
        "generated result stream column ordinals must be dense and zero-based"
    );

    let mut contradictory_max = valid_generated_manifest();
    contradictory_max.result_streams[0].row_count_max = Some(2);
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&resolved_response_with_manifest(
            contradictory_max
        ))
        .is_err(),
        "exactly-one result streams must not declare row_count_max above one"
    );
}

#[test]
fn generated_manifest_boundary_validation_rejects_invalid_permission_policy() {
    let mut missing_permissions = valid_generated_manifest();
    missing_permissions.required_permissions.clear();
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&resolved_response_with_manifest(
            missing_permissions
        ))
        .is_err(),
        "resolved manifests must carry explicit required permissions"
    );

    let mut uppercase_permission = valid_generated_manifest();
    uppercase_permission.required_permissions[0].id = "Andromeda.Execute".to_string();
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&resolved_response_with_manifest(
            uppercase_permission
        ))
        .is_err(),
        "permission ids must stay canonical lower-case boundary metadata"
    );

    let mut policy_hash_collision = valid_generated_manifest();
    policy_hash_collision.policy_version = policy_hash_collision.contract_hash.clone();
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&resolved_response_with_manifest(
            policy_hash_collision
        ))
        .is_err(),
        "policy_version must remain distinct from contract_hash"
    );

    let mut empty_policy_version = valid_generated_manifest();
    empty_policy_version.policy_version.clear();
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&resolved_response_with_manifest(
            empty_policy_version
        ))
        .is_err(),
        "resolved manifests must carry a 32-byte policy_version"
    );

    let mut zero_policy_version = valid_generated_manifest();
    zero_policy_version.policy_version = vec![0; 32];
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&resolved_response_with_manifest(
            zero_policy_version
        ))
        .is_err(),
        "resolved manifests must reject zero policy_version"
    );

    let mut zero_catalog_version = valid_generated_manifest();
    zero_catalog_version.catalog_version = 0;
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&resolved_response_with_manifest(
            zero_catalog_version
        ))
        .is_err(),
        "resolved manifests must reject zero CatalogVersion"
    );

    let mut missing_stats_version = valid_generated_manifest();
    missing_stats_version.stats_version = None;
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&resolved_response_with_manifest(
            missing_stats_version
        ))
        .is_err(),
        "resolved manifests must carry ProcedureContractBinding stats_version"
    );

    let mut zero_stats_version = valid_generated_manifest();
    zero_stats_version.stats_version = Some(0);
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&resolved_response_with_manifest(
            zero_stats_version
        ))
        .is_err(),
        "resolved manifests must reject zero ProcedureContractBinding stats_version"
    );
}

#[test]
fn catalog_manifest_resolution_resolved_response_must_match_manifest_binding_identity() {
    let manifest = valid_generated_manifest();

    let mut wrong_hash = resolved_response_with_manifest(manifest.clone());
    wrong_hash.resolved_contract_hash = Some(vec![0x55; 32]);
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&wrong_hash).is_err(),
        "resolved_contract_hash must match the resolved ProcedureManifest contract_hash"
    );

    let mut wrong_catalog = resolved_response_with_manifest(manifest);
    wrong_catalog.resolved_catalog_version = Some(10);
    assert!(
        validate_catalog_procedure_manifest_resolution_response(&wrong_catalog).is_err(),
        "resolved_catalog_version must match the resolved ProcedureManifest catalog_version"
    );
}

#[test]
fn catalog_manifest_resolution_status_policy_accepts_governed_error_statuses() {
    let governed_error_statuses = [
        (2, "STATUS_NOT_FOUND"),
        (3, "STATUS_CATALOG_VERSION_MISMATCH"),
        (4, "STATUS_CONTRACT_HASH_MISMATCH"),
        (5, "STATUS_NOT_SOURCE_GENERATOR_READY"),
        (6, "STATUS_PERMISSION_DENIED"),
        (7, "STATUS_UNSUPPORTED"),
        (8, "STATUS_MALFORMED"),
        (9, "STATUS_INTERNAL"),
        (10, "STATUS_CATALOG_NOT_READY"),
        (11, "STATUS_AUTH_REQUIRED"),
    ];

    for (status, name) in governed_error_statuses {
        let response = CatalogProcedureManifestResolutionResponse {
            protocol_major: 1,
            protocol_minor: 0,
            request_id: 78,
            trace_id: Some(format!("trace-{name}")),
            status,
            manifest: None,
            resolved_contract_hash: None,
            resolved_catalog_version: None,
            current_catalog_version: Some(9),
            diagnostic_code: Some(name.to_string()),
        };

        validate_catalog_procedure_manifest_resolution_response(&response)
            .unwrap_or_else(|error| panic!("{name} should satisfy response validation: {error}"));
    }
}

#[test]
fn catalog_manifest_resolution_error_statuses_reject_resolved_payload_fields() {
    let base = CatalogProcedureManifestResolutionResponse {
        protocol_major: 1,
        protocol_minor: 0,
        request_id: 80,
        trace_id: Some("trace-error-status".to_string()),
        status: 2,
        manifest: None,
        resolved_contract_hash: None,
        resolved_catalog_version: None,
        current_catalog_version: Some(9),
        diagnostic_code: Some("STATUS_NOT_FOUND".to_string()),
    };

    let cases = vec![
        (
            "manifest",
            CatalogProcedureManifestResolutionResponse {
                manifest: Some(valid_generated_manifest()),
                ..base.clone()
            },
        ),
        (
            "resolved_contract_hash",
            CatalogProcedureManifestResolutionResponse {
                resolved_contract_hash: Some(vec![0x11; 32]),
                ..base.clone()
            },
        ),
        (
            "resolved_catalog_version",
            CatalogProcedureManifestResolutionResponse {
                resolved_catalog_version: Some(9),
                ..base
            },
        ),
    ];

    for (field, response) in cases {
        assert!(
            validate_catalog_procedure_manifest_resolution_response(&response).is_err(),
            "non-resolved response must reject {field}"
        );
    }
}

#[test]
fn catalog_manifest_resolution_status_policy_rejects_unspecified_and_unknown_statuses() {
    for (status, name) in [(0, "STATUS_UNSPECIFIED"), (12, "future unknown status")] {
        let response = CatalogProcedureManifestResolutionResponse {
            protocol_major: 1,
            protocol_minor: 0,
            request_id: 79,
            trace_id: None,
            status,
            manifest: None,
            resolved_contract_hash: None,
            resolved_catalog_version: None,
            current_catalog_version: Some(9),
            diagnostic_code: Some(name.to_string()),
        };

        assert!(
            validate_catalog_procedure_manifest_resolution_response(&response).is_err(),
            "{name} must not satisfy response validation"
        );
    }
}

#[test]
fn catalog_resolution_rejects_unspecified_status() {
    let response = CatalogProcedureManifestResolutionResponse {
        protocol_major: 1,
        protocol_minor: 0,
        request_id: 81,
        trace_id: None,
        status: 0,
        manifest: None,
        resolved_contract_hash: None,
        resolved_catalog_version: None,
        current_catalog_version: Some(9),
        diagnostic_code: Some("STATUS_UNSPECIFIED".to_string()),
    };

    assert!(
        validate_catalog_procedure_manifest_resolution_response(&response).is_err(),
        "STATUS_UNSPECIFIED must not satisfy catalog resolution response validation"
    );
}

#[test]
fn catalog_resolution_rejects_protobuf_unknown_status() {
    let response = CatalogProcedureManifestResolutionResponse {
        protocol_major: 1,
        protocol_minor: 0,
        request_id: 82,
        trace_id: None,
        status: 12,
        manifest: None,
        resolved_contract_hash: None,
        resolved_catalog_version: None,
        current_catalog_version: Some(9),
        diagnostic_code: Some("STATUS_UNKNOWN_FUTURE".to_string()),
    };

    assert!(
        validate_catalog_procedure_manifest_resolution_response(&response).is_err(),
        "unknown protobuf status values must not satisfy catalog resolution response validation"
    );
}

proptest! {
    #[test]
    fn prop_protocol_version_roundtrip(major in 0u32..=1000, minor in 0u32..=1000) {
        let version = ProtocolVersion { major, minor };
        let bytes = version.encode_to_vec();
        let decoded = ProtocolVersion::decode(bytes.as_slice())
            .expect("Decode should succeed");

        prop_assert_eq!(version, decoded);
    }

    #[test]
    fn prop_frame_envelope_determinism(
        catalog_version in 0u64..=u64::MAX,
        request_id in 0u64..=u64::MAX,
        session_id in 0u64..=u64::MAX,
    ) {
        let envelope = FrameEnvelope {
            protocol_version: Some(ProtocolVersion { major: 1, minor: 0 }),
            contract_hash: vec![42u8; 32],
            catalog_version,
            request_id,
            session_id,
            tx_id: None,
            payload_kind: 5,
            payload: vec![1, 2, 3],
        };

        let bytes1 = envelope.encode_to_vec();
        let bytes2 = envelope.encode_to_vec();

        prop_assert_eq!(bytes1, bytes2, "Must serialize deterministically");
    }

    #[test]
    fn prop_rpc_batch_roundtrip(
        batch_index in 0u64..=1000,
        rows_emitted in 0u64..=1_000_000,
    ) {
        let batch = RpcBatch {
            result_name: "result".to_string(),
            batch_index,
            rows_emitted,
            structured_payload: vec![],
            row_count_exact: None,
            terminal_batch: false,
        };

        let bytes = batch.encode_to_vec();
        let decoded = RpcBatch::decode(bytes.as_slice())
            .expect("Decode should succeed");

        prop_assert_eq!(batch, decoded);
    }
}

// Test: Verify known hash values for specific messages (contract binding)
#[test]
fn test_known_message_encoding_contracts() {
    // These are canonical encodings; if they change, it indicates schema drift.

    // ProtocolVersion(1, 0) must always encode field 1 as varint 1. The
    // zero-valued minor field is omitted by Protobuf canonical encoding.
    let version_1_0 = ProtocolVersion { major: 1, minor: 0 };
    let expected_bytes = vec![0x08, 0x01];
    let actual_bytes = version_1_0.encode_to_vec();

    assert_eq!(
        actual_bytes, expected_bytes,
        "ProtocolVersion(1, 0) encoding contract changed; verify compatibility"
    );
}

#[test]
fn test_field_presence_preservation() {
    // Optional fields must preserve None/Some distinction
    let completion_with_lsn = RpcCompletion {
        status: 1,
        rows_affected: None,
        tx_id: None,
        request_id: None,
        session_id: None,
        trace_id: None,
        transaction_outcome: 2,
        durable_lsn: Some(12345),
        result_row_counts: vec![],
    };

    let completion_without_lsn = RpcCompletion {
        status: 1,
        rows_affected: None,
        tx_id: None,
        request_id: None,
        session_id: None,
        trace_id: None,
        transaction_outcome: 2,
        durable_lsn: None,
        result_row_counts: vec![],
    };

    let bytes_with = completion_with_lsn.encode_to_vec();
    let bytes_without = completion_without_lsn.encode_to_vec();

    assert_ne!(
        bytes_with, bytes_without,
        "Optional field presence must affect encoding"
    );

    // Verify roundtrip preserves the distinction
    let decoded_with = RpcCompletion::decode(bytes_with.as_slice()).unwrap();
    let decoded_without = RpcCompletion::decode(bytes_without.as_slice()).unwrap();

    assert_eq!(decoded_with.durable_lsn, Some(12345));
    assert_eq!(decoded_without.durable_lsn, None);
}

#[test]
fn test_no_codec_panics_on_malformed_input() {
    // Verify that malformed bytes don't cause panics
    let malformed_inputs = vec![
        vec![],                             // Empty
        vec![0xFF, 0xFF, 0xFF, 0xFF],       // Invalid varint
        vec![0x08, 0xFF, 0xFF, 0xFF, 0xFF], // Truncated field
    ];

    for malformed in malformed_inputs {
        // These should not panic; they may error, but not panic
        let result = FrameEnvelope::decode(malformed.as_slice());
        // We don't assert success, just that it doesn't panic
        let _ = result;
    }
}
