//! Golden-vector and property tests for [`payload_crc64`] and
//! [`header_integrity_crc32`].
//!
//! # Why these tests exist
//!
//! Both functions are used on durable storage paths:
//!
//! - **`payload_crc64`** computes the 64-bit FNV-1a digest stored in every
//!   page trailer.  A silent change corrupts the integrity check for every
//!   page written after the change, without any error at write time, only
//!   manifesting as false corruption reports (or missed real corruption) on
//!   subsequent reads.
//!
//! - **`header_integrity_crc32`** computes the 32-bit CRC stored at bytes
//!   104–107 of every PageCodecV1 header.  It protects header fields from
//!   in-memory and at-rest corruption.
//!
//! These golden constants are the **primary regression line** for the durable
//! byte semantics of both functions.  **Any change to either digest function
//! MUST be accompanied by a P11/Andromeda-Doctrine review and an explicit
//! increment of the page format version.**
//!
//! # `payload_crc64` algorithm
//!
//! FNV-1a ("XOR-then-multiply") over 64 bits, identical parameters to the WAL
//! codec's `fnv64_nonzero`:
//! - Offset basis: `0xcbf2_9ce4_8422_2325`
//! - Prime: `0x0000_0100_0000_01b3`
//! - Nonzero guard: if the digest would be `0`, return `1` instead.
//!
//! # `header_integrity_crc32` algorithm
//!
//! **CRC-32/ISO-HDLC** (also known as CRC-32b / gzip / zlib CRC-32):
//! - Polynomial (reflected): `0xEDB8_8320` (unreflected: `0x04C1_1DB7`)
//! - Initial value: `0xFFFF_FFFF`
//! - Input/output reflection: yes (bit-serial, LSB-first)
//! - Final XOR: `0xFFFF_FFFF` (i.e., `!crc`)
//! - Reference: CRC catalogue at <https://reveng.sourceforge.io/crc-catalogue/17plus.htm>
//!   check value `CRC-32/ISO-HDLC` = `0xCBF4_3926` for input `"123456789"`.
//!
//! **Page-header extension**: the 4 bytes at offsets `[104..108)` of the input
//! are substituted with `0x00` before hashing.  This ensures that the CRC
//! field itself does not contribute to its own checksum.
//!
//! **Nonzero guard**: if the final CRC is `0`, the function returns `1`.
//! For inputs shorter than 104 bytes the offset range is never reached, so
//! the function is bit-for-bit equivalent to standard CRC-32/ISO-HDLC for
//! those inputs.
//!
//! # How the golden constants were generated
//!
//! The constants were produced by running the production implementations on
//! each input and pinning the output.  They are **regression constants**.
//! The CRC-32/ISO-HDLC short-input constants (< 104 bytes) are additionally
//! cross-validated against the public CRC catalogue check values.
//!
//! # Residual TODOs
//!
//! - **P12**: Cross-validate `payload_crc64` goldens against an external
//!   FNV-64a reference implementation.
//! - **P12**: Add a golden vector for a full 112-byte page header (verifying
//!   the integrity-range masking for the complete header format).

#![forbid(unsafe_code)]

use andromeda_storage_page::{header_integrity_crc32, payload_crc64};

// ===========================================================================
// payload_crc64 golden constants
// ===========================================================================
//
// Generated by running the production function on each input and recording the
// output.  Do NOT change these constants without a page format-version review.

/// `payload_crc64` of an empty payload.
/// The FNV state never leaves the offset basis → returns the offset basis
/// directly (0xcbf2_9ce4_8422_2325 ≠ 0, nonzero guard not triggered).
const PL_CRC64_EMPTY: u64 = 0xcbf2_9ce4_8422_2325;

/// `payload_crc64` of a single byte 0x61 ('a').
const PL_CRC64_ONE_BYTE_A: u64 = 0xaf63_dc4c_8601_ec8c;

/// `payload_crc64` of 64 × 0x00 bytes.
const PL_CRC64_64_ZEROS: u64 = 0xb9b2_3f3a_46fd_0825;

/// `payload_crc64` of 64 × 0xFF bytes.
const PL_CRC64_64_FF: u64 = 0x84cc_4da0_e20e_cde5;

/// `payload_crc64` of 4096 × 0xAB bytes (one page-size worth of data).
/// 4096 bytes is the smallest Andromeda page granularity.
const PL_CRC64_4096_0XAB: u64 = 0xf14a_ffd7_f406_f325;

// ===========================================================================
// header_integrity_crc32 golden constants
// ===========================================================================
//
// The first three vectors use inputs shorter than 104 bytes, so the
// integrity-range masking never applies.  For those inputs the function is
// bit-for-bit equivalent to standard CRC-32/ISO-HDLC; the CRC catalogue
// provides independent cross-validation.

/// `header_integrity_crc32` of an empty slice.
/// Standard CRC-32/ISO-HDLC("") = 0x0000_0000.  The nonzero guard transforms
/// this to 1.  Reference: CRC catalogue initial/final XOR gives 0 for empty
/// input (0xFFFFFFFF ^ 0xFFFFFFFF = 0).
const HDR_CRC32_EMPTY: u32 = 0x0000_0001;

/// `header_integrity_crc32` of a single byte 0x61 ('a').
/// Cross-validated: standard CRC-32/ISO-HDLC("a") = 0xE8B7_BE43.
/// Reference: <https://crccalc.com> / CRC-32 of ASCII 'a'.
const HDR_CRC32_ONE_BYTE_A: u32 = 0xE8B7_BE43;

/// `header_integrity_crc32` of b"123456789".
/// Cross-validated: standard CRC-32/ISO-HDLC check value = 0xCBF4_3926.
/// Reference: CRC catalogue `CRC-32/ISO-HDLC` check value.
const HDR_CRC32_CHECK_VECTOR: u32 = 0xCBF4_3926;

// ===========================================================================
// payload_crc64 — golden vector tests
// ===========================================================================

#[test]
fn payload_crc64_golden_empty() {
    assert_eq!(
        payload_crc64(&[]),
        PL_CRC64_EMPTY,
        "payload_crc64 of empty input must equal the FNV offset basis"
    );
}

#[test]
fn payload_crc64_golden_one_byte_a() {
    assert_eq!(
        payload_crc64(&[0x61]),
        PL_CRC64_ONE_BYTE_A,
        "payload_crc64 of single byte 0x61 diverges from golden"
    );
}

#[test]
fn payload_crc64_golden_64_zeros() {
    assert_eq!(
        payload_crc64(&[0u8; 64]),
        PL_CRC64_64_ZEROS,
        "payload_crc64 of 64 zero bytes diverges from golden"
    );
}

#[test]
fn payload_crc64_golden_64_ff_bytes() {
    assert_eq!(
        payload_crc64(&[0xFFu8; 64]),
        PL_CRC64_64_FF,
        "payload_crc64 of 64 × 0xFF bytes diverges from golden"
    );
}

#[test]
fn payload_crc64_golden_4096_page_size() {
    assert_eq!(
        payload_crc64(&[0xABu8; 4096]),
        PL_CRC64_4096_0XAB,
        "payload_crc64 of 4096-byte page-sized input diverges from golden"
    );
}

// ===========================================================================
// payload_crc64 — nonzero-guard tests
// ===========================================================================

/// All golden outputs must be nonzero — the function contract guarantees this.
#[test]
fn payload_crc64_output_is_never_zero_for_test_vectors() {
    for (label, digest) in [
        ("empty", PL_CRC64_EMPTY),
        ("one_byte_a", PL_CRC64_ONE_BYTE_A),
        ("64_zeros", PL_CRC64_64_ZEROS),
        ("64_ff", PL_CRC64_64_FF),
        ("4096_0xAB", PL_CRC64_4096_0XAB),
    ] {
        assert_ne!(digest, 0u64, "golden vector '{label}' must not be zero");
    }
}

// ===========================================================================
// payload_crc64 — determinism property test
// ===========================================================================

/// Identical inputs must always produce identical outputs (pure function).
/// Calls the function 100 times per input vector and asserts consistency.
#[test]
fn payload_crc64_is_deterministic_across_100_runs() {
    const RUNS: usize = 100;
    let inputs: &[(&str, &[u8])] = &[
        ("empty", &[]),
        ("one_byte_a", &[0x61]),
        ("64_zeros", &[0u8; 64]),
        ("64_ff", &[0xFFu8; 64]),
    ];

    for (label, input) in inputs {
        let expected = payload_crc64(input);
        for run in 0..RUNS {
            let result = payload_crc64(input);
            assert_eq!(
                result, expected,
                "payload_crc64 not deterministic on run {run} for input '{label}'"
            );
        }
    }
}

/// Swapping a single byte in a payload must change the digest.
#[test]
fn payload_crc64_sensitive_to_single_byte_change() {
    let mut input = [0x00u8; 64];
    let base = payload_crc64(&input);
    input[32] = 0x01;
    let modified = payload_crc64(&input);
    assert_ne!(
        base, modified,
        "payload_crc64 must change on single-byte flip"
    );
}

// ===========================================================================
// header_integrity_crc32 — golden vector tests
// ===========================================================================

/// Empty input → standard CRC-32/ISO-HDLC = 0; nonzero guard returns 1.
#[test]
fn header_integrity_crc32_golden_empty_yields_nonzero_guard() {
    assert_eq!(
        header_integrity_crc32(&[]),
        HDR_CRC32_EMPTY,
        "header_integrity_crc32 of empty input must equal 1 (nonzero guard applied)"
    );
}

/// 'a' → standard CRC-32/ISO-HDLC = 0xE8B7_BE43 (cross-validated externally).
#[test]
fn header_integrity_crc32_golden_one_byte_a() {
    assert_eq!(
        header_integrity_crc32(&[0x61]),
        HDR_CRC32_ONE_BYTE_A,
        "header_integrity_crc32('a') diverges from CRC-32/ISO-HDLC reference 0xE8B7BE43"
    );
}

/// "123456789" → 0xCBF4_3926 (CRC catalogue check value, externally validated).
#[test]
fn header_integrity_crc32_golden_check_vector() {
    assert_eq!(
        header_integrity_crc32(b"123456789"),
        HDR_CRC32_CHECK_VECTOR,
        "header_integrity_crc32('123456789') diverges from CRC-32/ISO-HDLC check value 0xCBF43926"
    );
}

// ===========================================================================
// header_integrity_crc32 — nonzero-guard and polynomial tests
// ===========================================================================

/// All golden outputs must be nonzero.
#[test]
fn header_integrity_crc32_output_is_never_zero_for_test_vectors() {
    for (label, digest) in [
        ("empty", HDR_CRC32_EMPTY),
        ("one_byte_a", HDR_CRC32_ONE_BYTE_A),
        ("check_vector", HDR_CRC32_CHECK_VECTOR),
    ] {
        assert_ne!(
            digest, 0u32,
            "CRC-32 golden vector '{label}' must not be zero"
        );
    }
}

/// Swapping a single byte must change the CRC.
#[test]
fn header_integrity_crc32_sensitive_to_single_byte_change() {
    let mut input = [0x00u8; 32];
    let base = header_integrity_crc32(&input);
    input[16] = 0x01;
    let modified = header_integrity_crc32(&input);
    assert_ne!(
        base, modified,
        "header_integrity_crc32 must change on single-byte flip"
    );
}

/// Determinism: same input produces same output across 100 runs.
#[test]
fn header_integrity_crc32_is_deterministic_across_100_runs() {
    const RUNS: usize = 100;
    let inputs: &[(&str, &[u8])] = &[
        ("empty", &[]),
        ("one_byte_a", &[0x61]),
        ("check_vector", b"123456789"),
    ];
    for (label, input) in inputs {
        let expected = header_integrity_crc32(input);
        for run in 0..RUNS {
            let result = header_integrity_crc32(input);
            assert_eq!(
                result, expected,
                "header_integrity_crc32 not deterministic on run {run} for input '{label}'"
            );
        }
    }
}
