[package]
name = "andromeda-observe"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
andromeda-audit.workspace = true
andromeda-error.workspace = true
andromeda-hardware.workspace = true
andromeda-observability.workspace = true
andromeda-types.workspace = true

[dev-dependencies]
andromeda-storage-page.workspace = true
andromeda-storage-placement.workspace = true
