[package]
name = "andromeda-observe"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
andromeda-core.workspace = true
andromeda-digest.workspace = true
andromeda-error.workspace = true
andromeda-hardware.workspace = true
andromeda-types.workspace = true

[dev-dependencies]
andromeda-storage.workspace = true
