[package]
name = "andromeda-rpc-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
andromeda-error.workspace = true
andromeda-procedure-contract.workspace = true
andromeda-types.workspace = true

[dev-dependencies]
andromeda-principal.workspace = true
