[package]
name = "andromeda-srpl-ir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
andromeda-error.workspace = true
andromeda-procedure-contract.workspace = true
andromeda-srpl-cardinality.workspace = true
andromeda-types.workspace = true
