[package]
name = "andromeda-result-stream"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
andromeda-core.workspace = true
andromeda-observe.workspace = true
andromeda-proto.workspace = true
andromeda-rpc-protocol.workspace = true
andromeda-srpl-cardinality.workspace = true
andromeda-storage.workspace = true
andromeda-tx.workspace = true
tokio = { workspace = true, features = ["sync"] }
