[package]
name = "andromeda-recovery"
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"
publish = false

[dependencies]
andromeda-error.workspace = true
andromeda-manifest.workspace = true
andromeda-storage-heap.workspace = true
andromeda-storage-index.workspace = true
andromeda-storage-page.workspace = true
andromeda-time.workspace = true
andromeda-transaction-log.workspace = true
andromeda-types.workspace = true
andromeda-wal.workspace = true

[dev-dependencies]
andromeda-observability.workspace = true
andromeda-observe.workspace = true
proptest.workspace = true
andromeda-mvcc.workspace = true
tokio.workspace = true
