[package]
name = "andromeda-srpl-execution-adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
andromeda-error.workspace = true
andromeda-procedure-contract.workspace = true
andromeda-srpl-ir.workspace = true

[dev-dependencies]
andromeda-types.workspace = true
