[package]
name = "andromeda-tx"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
andromeda-locking.workspace = true
andromeda-mvcc.workspace = true
andromeda-savepoint.workspace = true
andromeda-transaction.workspace = true
andromeda-transaction-log.workspace = true
