[package]
name = "andromeda-srpl-interpreter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
andromeda-contract.workspace = true
andromeda-error.workspace = true
andromeda-srpl-execution-adapter.workspace = true
andromeda-srpl-ir.workspace = true

[dev-dependencies]
andromeda-srpl-test-fixtures.workspace = true
