[package]
name = "andromeda-procedure-contract"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
andromeda-digest.workspace = true
andromeda-error.workspace = true
andromeda-security-contract.workspace = true
andromeda-structured-object.workspace = true
andromeda-types.workspace = true
