[package]
name = "andromeda-rpc-codec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
andromeda-catalog-store.workspace = true
andromeda-error.workspace = true
andromeda-procedure-contract.workspace = true
andromeda-proto.workspace = true
andromeda-proto-wire.workspace = true
andromeda-rpc-protocol.workspace = true
andromeda-types.workspace = true
