[package]
name = "andromeda-srpl-parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
andromeda-contract.workspace = true
andromeda-srpl-ast.workspace = true
andromeda-srpl-cardinality.workspace = true
andromeda-srpl-diagnostics.workspace = true
andromeda-srpl-lexer.workspace = true
andromeda-types.workspace = true
