[package]
name = "andromeda-admission"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
andromeda-error.workspace = true
andromeda-hardware.workspace = true
andromeda-observability.workspace = true
andromeda-principal.workspace = true
andromeda-procedure-contract.workspace = true
andromeda-resource.workspace = true
andromeda-result-stream.workspace = true
andromeda-storage-page.workspace = true
andromeda-storage-placement.workspace = true
andromeda-structured-object.workspace = true
andromeda-types.workspace = true

[dev-dependencies]
andromeda-observe.workspace = true
