[package]
name = "andromeda-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
andromeda-bench.workspace = true
andromeda-catalog.workspace = true
andromeda-core.workspace = true
andromeda-exec.workspace = true
andromeda-observe.workspace = true
andromeda-quic.workspace = true
andromeda-srpl.workspace = true
andromeda-storage.workspace = true
sha2 = "0.11.0"
