[package]
name = "andromeda-catalog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
andromeda-contract.workspace = true
andromeda-digest.workspace = true
andromeda-error.workspace = true
andromeda-observe.workspace = true
andromeda-proto.workspace = true
andromeda-time.workspace = true
andromeda-types.workspace = true

[dev-dependencies]
andromeda-storage.workspace = true
