[package]
name = "andromeda-catalog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
andromeda-core.workspace = true
andromeda-observe.workspace = true
andromeda-proto.workspace = true

[dev-dependencies]
andromeda-storage.workspace = true

