mod binary;
mod decode;
mod encode;
mod integrity;
mod policy;
mod validation;

pub(super) use encode::{build_entry_with_crc, build_header, build_trailer};
pub(super) use validation::validate_index_contract;

pub const SEGMENT_INDEX_V0_MAGIC: [u8; 8] = *b"ANDSGIX0";
pub const SEGMENT_INDEX_V0_FORMAT_MAJOR: u16 = 1;
pub const SEGMENT_INDEX_V0_FORMAT_MINOR: u16 = 0;
pub const SEGMENT_INDEX_V0_BYTE_ORDER: u16 = 0x0102;
pub const SEGMENT_INDEX_V0_HEADER_LEN: usize = 256;
pub const SEGMENT_INDEX_V0_ENTRY_LEN: usize = 160;
pub const SEGMENT_INDEX_V0_TRAILER_LEN: usize = 96;
pub const SEGMENT_INDEX_V0_MAX_ENTRIES: u64 = 16_777_216;
pub const SEGMENT_INDEX_V0_MAX_EXTENSION_BYTES: u64 = 1024 * 1024;

pub const SEGMENT_INDEX_V0_FLAG_PUBLISHED_COLD_ONLY: u32 = 0x0000_0001;
pub const SEGMENT_INDEX_V0_FLAG_CONTIGUOUS_PAGE_RANGES: u32 = 0x0000_0002;
pub const SEGMENT_INDEX_V0_FLAG_FORENSIC_HOLD: u32 = 0x0000_0008;

const KNOWN_FLAGS: u32 = SEGMENT_INDEX_V0_FLAG_PUBLISHED_COLD_ONLY
    | SEGMENT_INDEX_V0_FLAG_CONTIGUOUS_PAGE_RANGES
    | SEGMENT_INDEX_V0_FLAG_FORENSIC_HOLD;

const PAGE_SIZE_POLICY_MIXED: u32 = 0;
const PAGE_SIZE_POLICY_16K: u32 = 1;
const PAGE_SIZE_POLICY_32K: u32 = 2;

const PAGE_SIZE_TAG_16K: u16 = 1;
const PAGE_SIZE_TAG_32K: u16 = 2;
const SEGMENT_STATE_TAG_BUILDING_HOT_SNAPSHOT: u16 = 1;
const SEGMENT_STATE_TAG_SEALED: u16 = 2;
const SEGMENT_STATE_TAG_PUBLISHED_COLD: u16 = 3;
const EXTENSION_REQUIRED_FLAG: u16 = 0x0001;

const HEADER_TOTAL_LEN_OFFSET: usize = 16;
const HEADER_CRC_OFFSET: usize = 24;
const HEADER_FLAGS_OFFSET: usize = 28;
const HEADER_DATABASE_ID_OFFSET: usize = 32;
const HEADER_SNAPSHOT_ID_OFFSET: usize = 40;
const HEADER_SEGMENT_INDEX_ID_OFFSET: usize = 48;
const HEADER_MANIFEST_VERSION_OFFSET: usize = 56;
const HEADER_BASE_CHECKPOINT_LSN_OFFSET: usize = 64;
const HEADER_REQUIRED_WAL_START_LSN_OFFSET: usize = 72;
const HEADER_ENTRY_OFFSET_OFFSET: usize = 80;
const HEADER_ENTRY_COUNT_OFFSET: usize = 88;
const HEADER_ENTRY_LEN_OFFSET: usize = 96;
const HEADER_PAGE_SIZE_POLICY_TAG_OFFSET: usize = 100;
const HEADER_EXTENSION_OFFSET_OFFSET: usize = 104;
const HEADER_EXTENSION_LEN_OFFSET: usize = 112;
const HEADER_FIRST_SEGMENT_ID_OFFSET: usize = 120;
const HEADER_LAST_SEGMENT_ID_OFFSET: usize = 128;
const HEADER_FIRST_PAGE_ID_OFFSET: usize = 136;
const HEADER_LAST_PAGE_ID_OFFSET: usize = 144;
const HEADER_MIN_PAGE_LSN_OFFSET: usize = 152;
const HEADER_MAX_PAGE_LSN_OFFSET: usize = 160;
const HEADER_TOTAL_PAGE_COUNT_OFFSET: usize = 168;
const HEADER_PARENT_MANIFEST_HASH_OFFSET: usize = 176;
const HEADER_ENTRY_TABLE_SHA256_OFFSET: usize = 208;
const HEADER_ENTRY_TABLE_CRC64_OFFSET: usize = 240;
const HEADER_RESERVED_248_OFFSET: usize = 248;

const ENTRY_RESERVED_52_OFFSET: usize = 52;
const ENTRY_CRC_OFFSET: usize = 156;

const TRAILER_FILE_SHA_OFFSET: usize = 8;
const TRAILER_ROOT_HASH_OFFSET: usize = 40;
const TRAILER_CRC_OFFSET: usize = 72;
const TRAILER_FLAGS_OFFSET: usize = 76;
const TRAILER_RESERVED_80_OFFSET: usize = 80;
